### ISSUE TITLE
No output when NODE_ENV is 'development'

### ISSUE THREAD

**Issue by scan** [nodester/nodester-cli#52]
In my `.profile`, I have set `NODE_ENV` to `development` so I can test in exactly that condition. The result is that the `nodester` command never gives me any output. It just looks like this:

``` bash
$> nodester
$> 
```

And that's it. When I set `NODE_ENV` to empty, it works fine again.

If that is expected behaviour, please state so in the docs.

**Comment by alejandro** [comment]
Yeah probably because of this https://github.com/nodester/nodester-cli/blob/master/lib/log.js#L41-60, mostly because we set the flag to "production" in userland (https://github.com/nodester/nodester-cli/blob/master/bin/nodester.js#L8), so we can run tests without killing the test server.

I fixed it in my fork, you can install it with:

´npm install -g https://github.com/alejandro/nodester-cli/tarball/master`

:@chrismatthieu should I make a PR?

/be

**Comment by chrismatthieu** [comment]
yes, please :)
